# 1. Numpy Review

In [2]:
import numpy as np
import torch

## 1) 1D Array with NumPy

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 2) 2D Array with NumPy (행렬)

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]]) # 4 by 3 matrix
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# 2. PyTorch Tensor

## 1) 1D Array with PyTorch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # element
print(t[2:5], t[4:-1]) # slicing
print(t[:2], t[3:]) # slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2) 2D Array with PyTorch

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# 3. Broadcasting
* 행렬의 덧셈, 뺄셈 시 크기가 같아야 한다.
* 행렬의 곱셈 시 앞 행렬의 마지막 차원과 뒤 행렬의 첫 번째 차원이 같아야 한다.
* 하지만, PyTorch에서는 다른 크기의 행렬의 연산을 Broadcasting을 통해 자동으로 조건에 맞추어 진행한다.
* 자동으로 실행되므로, 사용자 입장에서 주의할 필요가 있다. (예상치 못한 오류를 발생시킬 수 있음)

In [15]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2) # 행렬 크기 같으므로 자연스러움

tensor([[5., 5.]])


In [16]:
# Vector + Scalar : 작은 크기를 큰 크기로 맞춰줌
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector : 마찬가지로 작은 차원을 큰 차원으로 변환해줌
m1 = torch.FloatTensor([[1, 2]]) # 2 by 1 -> 2 by 2
m2 = torch.FloatTensor([[3], [4]]) # 1 by 2 -> 2 by 2
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


# 4. Multiplication vs Matrix Multiplication

In [19]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
# Mul : Elementwise mul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 by 2
print('Shape of Matrix 2: ', m2.shape) # 2 by 1 -> 2 by 2
print(m1 * m2)
print(m1.mul(m2))

# Matmul : 행렬곱
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 by 2
print('Shape of Matrix 2: ', m2.shape) # 2 by 1
# broadcasting 일어나지 않음
print(m1.matmul(m2)) # 2 by 1


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


# 5. Mean

In [20]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [21]:
# Can't use mean() on inteagers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


* You can also use `t.mean` for higher rank tensors to get mean of all elements, or mean by particular dimension

In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.mean()) # 전체 element의 평균
print(t.mean(dim=0)) # dim 0을 없앰, 즉 각 열의 평균 (2 by 2 -> 1 by 2)
print(t.mean(dim=1)) # dim 1을 없앰, 즉 각 행의 평균
print(t.mean(dim=-1)) # 마지막 dim을 없앰

print(t.mean(dim=0).shape)
print(t.mean(dim=1).shape)
print(t.mean(dim=-1).shape)

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
torch.Size([2])
torch.Size([2])
torch.Size([2])


# 6. Sum

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.sum())
print(t.sum(dim=0)) # 행끼리 더함
print(t.sum(dim=1)) # 열끼리 더함
print(t.sum(dim=-1)) # 마지막 차원끼리 더함

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# 7. Max and Argmax

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The `max` operator returns one value if it is called without an argument

In [32]:
print(t.max()) # Returns one value: max

tensor(4.)


The `max` operator returns 2 values when called with dimension specified.
* The first value is the maximum value, and the second value is the argmax: the index of the max element.

In [33]:
print(t.max(dim=0)) # Returns two values: max and argmax (행방향, 즉 상하방향의 값들 중 max 값)
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [34]:
print(t.max(dim=1)) # 열방향, 즉 좌우방향의 값들 중 max값
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# 8. View (NumPy의 Reshape)
* Shape를 수정할 수 있음

In [35]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
             
             [[6, 7, 8],
              [9, 10, 11]]]) # 2 by 2 by 3

ft = torch.FloatTensor(t) # numpy arr -> tensor
print(ft.shape)

torch.Size([2, 2, 3])


In [36]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [37]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# 9. Squeeze
* 특정 dimension의 element가 한 개인 경우 없앰

In [38]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [39]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [42]:
print(ft.squeeze(dim=0)) # 아무 반응 x
print(ft.squeeze(dim=1)) # 위와 같은 결과

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


# 10. Unsqueeze
* Squeeze의 반대로, 원하는 dimension을 추가해줌 (dimension을 꼭 명시해주어야 함)

In [43]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [44]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [45]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [46]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [47]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# 11. Type Casting
* Tensor의 datatype 바꾸기

In [48]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [49]:
print(lt.float()) # Long -> Float

tensor([1., 2., 3., 4.])


In [50]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [52]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# 12. Concatenate
* 두 tensor를 이어붙이기

In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [54]:
print(torch.cat([x, y], dim=0)) # 행을 concat
print(torch.cat([x, y], dim=1)) # 열을 concat

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# 13. Stacking
* cat보다 좀 더 편한 함수

In [55]:
# 3 개의 1D vector (2, )에 대해
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [56]:
print(torch.stack([x, y, z])) # 쌓을 방향은 default가 행방향
print(torch.stack([x, y, z], dim=1)) # 열 방향으로 쌓음

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


* cat의 경우, unsqueeze를 통해 (1, 2)로 만들어 주어야 사용 가능함

In [57]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0) ], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# 14. Ones and Zeros

In [59]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [60]:
print(torch.ones_like(x)) # x와 같은 shape의 ones
print(torch.zeros_like(x)) # x와 같은 shape의 zeros
# device(CPU, GPU 등)도 x와 일치시켜야 함

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 15. In-place Operation

In [61]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [62]:
print(x.mul(2.)) # 원래 x를 바꾸지 않음
print(x)
print(x.mul_(2.)) # 메모리에 새로 선언하지 않고 x 자체를 바꿈
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


* PyTorch 자체에 garbage collector가 잘 설계되어 있어, 연산 속도가 크게 차이나지 않음